# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: 'npm' # See documentation for possible values
    directory: '/' # Location of package manifests
    ignore:
      # @nrwl deps should always be updated by running `npx nx migrate @nrwl/workspace`
      - dependency-name: '@nrwl/*'
      - dependency-name: 'nx'
      # NX managed packages should not be updated manually
      - dependency-name: '@types/jest'
      - dependency-name: '@types/node'

      - dependency-name: '@typescript-eslint/eslint-plugin'
      - dependency-name: '@typescript-eslint/parser'
      - dependency-name: 'eslint'
      - dependency-name: 'eslint-config-prettier'
      - dependency-name: 'eslint-plugin-import'
      - dependency-name: 'jest'
      - dependency-name: 'prettier'
      - dependency-name: 'ts-jest'
      - dependency-name: 'ts-node'
      - dependency-name: 'tslib'
      - dependency-name: 'ts-node'
      - dependency-name: 'typescript'
    schedule:
      interval: 'daily'
